import os

__version__ = "1.0.0"


class Package:
    def __init__(self):
        self.mods = []


class Mod:
    pass


def package():
    pkg = Package()
    pkg.path = os.path.dirname(__file__)
    pkg.name = os.path.basename(pkg.path)
    pkg.astro_version = "0.2.0"
    pkg.glia_version = "0.1.1"

    # -Generated by Astrocyte v0.2.0
    # -mod_glia__patch_extensions__VecStim__0
    mod_glia__patch_extensions__VecStim__0 = Mod()
    mod_glia__patch_extensions__VecStim__0.pkg_name = "patch_extensions"
    mod_glia__patch_extensions__VecStim__0.asset_name = "VecStim"
    mod_glia__patch_extensions__VecStim__0.variant = "0"
    mod_glia__patch_extensions__VecStim__0.namespace = "glia__patch_extensions"
    mod_glia__patch_extensions__VecStim__0._is_point_process = False
    mod_glia__patch_extensions__VecStim__0._is_artificial_cell = True
    mod_glia__patch_extensions__VecStim__0._name_statement = "ARTIFICIAL_CELL"
    mod_glia__patch_extensions__VecStim__0.pkg = pkg
    pkg.mods.append(mod_glia__patch_extensions__VecStim__0)
    # -##
    return pkg
