name: Black

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Black Check
      uses: jpetrucciani/black-check@20.9b1
      with:
        path: 'patch'
